# Generated by Django 5.2 on 2025-07-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='Static/avatars/default.png', upload_to='Static/avatars/'),
        ),
    ]
